name: acousticGS
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - torchaudio=2.3.1
  - pytorch-cuda=11.8
  - cuda-toolkit=11.8
  - gcc_linux-64=11
  - gxx_linux-64=11
  - pip
  - pip:
    - wandb
    - auraloss
    - matplotlib